### ISSUE TITLE
Prior Art and Literature Review

### ISSUE THREAD

**Issue by mewmew** [godbit/Sherlock#1]
Lust att kika på [Minority Report](http://www.imdb.com/title/tt0181689/) någon dag? =)

**Comment by godbit** [comment]
Haha lätt! Bra att sätt ribban liksom ;)

**Comment by karlek** [comment]
Hoppar på det här tåget och föreslår lördag kväll :cactus:

**Comment by karlek** [comment]
Hemma hos dig, pga din skärm är större

**Comment by mewmew** [comment]
:cactus: också på på lör!

**Comment by godbit** [comment]
Spikat hemma hos Draftlord/GODbit på lördag då! Jag ordnar med middag :smile_cat: 

Någon av er som råkar ha denna på "dvd" eller dylikt? :smirk:

**Comment by mewmew** [comment]
> Någon av er som råkar ha denna på "dvd" eller dylikt? smirk

Funkar mkv på USB?

**Comment by godbit** [comment]
Givetvis!

Jag gillar hur detta är det enda sättet som vi kan har en gruppchatt på xD

**Comment by karlek** [comment]
Här finns ju allt en behöver: emojis :cactus: 
__Markdown__ _support_

**Comment by godbit** [comment]
Sant! Ni ni är välkomna när som helst under hela lördagen :) Jag kommer förmodligen att dra och handla strax efter lunch men annars är jag hemma.

Exakt:
1. Det är det enda mediet där Robin har tillgång till emojis
2. *Vem* älskar inte att formatera sin chatt med markdown
3. Man kan ha tables i chatten (:heart_eyes_cat:)

Support | Messenger | Github Issues
------------ | ------------ | -------------
Gruppchatt | :+1: | :+1: 
Gruppchatt med Robin | :-1:  | :+1: 
Emojis | :+1: | :+1: 
Markdown | :crossed_fingers: | :+1:
Tables | :-1:  | :+1:  
Score | :neutral_face: | :star: :star: :star: :star: :star:
